### ISSUE TITLE
English version request

### ISSUE THREAD

**Issue by oneswitch** [MastaLomaster/mishkinamish#1]
This is brilliant. Reminds me of the Vocal Joystick... 

[Vocal Joystick blog post
](https://switchgaming.blogspot.com/2008/08/vocal-joystick-and-tongue-controller.html?q=vocal+joystick)

..but unlike Vocal Joystick, Mishkinamish works really well. Found you via Sasha Zenko's YouTube channel [No Hand's Let's Play](https://www.youtube.com/user/zenko1985/about), and found Sasha via a colleague at [SpecialEffect](https://www.specialeffect.org.uk/)

Please would you consider making an English version? Or an easy to find English language button? It would help lots more disabled people to play. This will work on game consoles too if using a Titan One / Titan Two device using the capture mode.

Fantastic work!

**Comment by MastaLomaster** [comment]
Please check the English version and let me know if I was not literate or something is clumsy and can be improved.

**Comment by oneswitch** [comment]
Many thanks. Here's my suggestions....

Change 1: "The program was not trained to work with some of the sounds. To train it press the "Train" button, keep silence for a while, then pronounce the sound several times.

To: Untrained. To enable, press "Train", then pause, then make your sound several times.


Change 2: "Save what it was trained"  ..... To: "Save"


Change 3: "Do not react on "K" and "Ch" when they are inside a word. Draw a red square if there was no silence before/after them"

To: Ignore "K" and "Ch" sounds when detected within other sounds (indicated via a red square).


Change 4: "Press keybouard buttons instead of mouse control"

To: Press keyboard buttons instead of mouse control.

**Comment by MastaLomaster** [comment]
Thank you for the suggestions. I included the changes in the latest draft #12, please check.

**Comment by oneswitch** [comment]
Top job. Thank you. :)
