### ISSUE TITLE
Latched / Toggle mode

### ISSUE THREAD

**Issue by oneswitch** [MastaLomaster/mishkinamish#2]
It would be very useful to have a latched / toggled option for the directions.

For example, using a Titan Two, it's possible to use Mishkinamish to play Playstation and Xbox games. If you want to walk forwards, you have to constantly say "Ehhh" which is very tiring.

To say "Ehhh" once to keep the associated UP control pressed, until saying "Ehhh" again to release, would be much less tiring.

**Comment by MastaLomaster** [comment]
I've added the "toggle" checkboxes. They can be combined with the "repeat" checkboxes. So that you make a sound once, and it starts to repeat pushing the key until you make a sound the second time.
Again, didn't have time to test it extensively. Waiting for your comments.

**Comment by oneswitch** [comment]
Seems to be working perfectly. Thanks so much. Immensely useful addition. :)
