### ISSUE TITLE
Stop / Start keyboard shortcut

### ISSUE THREAD

**Issue by oneswitch** [MastaLomaster/mishkinamish#4]
A friend of mine who uses his voice alone to play games (see [Voiced Gaming](https://www.youtube.com/channel/UCATjecPa4eylXKfWoVE59Uw))... was very impressed with MishkinaMish, especially how fast it responds... as seen in this [Playstation 4 Jetpack Joyride](https://www.youtube.com/watch?v=U-hQvZ0nGqQ) example.

One upgrade would really help him....

A keyboard short-cut to Stop/Start MishkinaMish.

...ideally that short-cut should be possible to change by the user (e.g. ALT+M)... He could then use it freely and easily alongside things like VoiceAttack, Dragon, GavPie and other speech to text software.

Fingers crossed you might find time for some of these things. Thank you for writing it.

**Comment by oneswitch** [comment]
Perhaps ALT+F5 would be a good method, if fixed?

**Comment by MastaLomaster** [comment]
Please check the latest version (draft #13). It has Alt+F5 hotkey. Not much tested, however.

**Comment by oneswitch** [comment]
Seems to work perfectly. Thank you!
